let stockProductos = [
    {id: 1, nombre: "Buzo 1", tipo: "buzo", cantidad: 1, desc: "Un buzo deportivo color negro, blanco y verde", precio: 1200, talle: "L", img: './img/buzo1.jpg'},
    {id: 2, nombre: "Buzo 2", tipo: "buzo", cantidad: 1, desc: "Un buzo deportivo color azul celeste", precio: 1100, talle: "L", img: './img/buzo2.jpg'},
    {id: 3, nombre: "Buzo 3", tipo: "buzo", cantidad: 1, desc: "Un buzo deportivo color camel", precio: 1200, talle: "M", img: './img/buzo3.jpg'},
    {id: 4, nombre: "Buzo 4", tipo: "buzo", cantidad: 1, desc: "Un buzo deportivo color rosado opaco", precio: 1400, talle: "M", img: './img/buzo4.jpg'},
    {id: 5, nombre: "Buzo 5", tipo: "buzo", cantidad: 1, desc: "Un conjunto deportivo color rosado, gris y negro", precio: 1200, talle: "S", img: './img/buzo5.jpg'},
    {id: 6, nombre: "Buzo 6", tipo: "buzo", cantidad: 1, desc: "Un buzo deprotivo color fucsia", precio: 1500, talle: "S", img: './img/buzo6.jpg'},
    {id: 7, nombre: "Remera 1", tipo: "remera", cantidad: 1, desc: "Una blusa elegante color verde oscuro satinado", precio: 500, talle: "L", img: './img/remera1.jpg'},
    {id: 8, nombre: "Remera 2", tipo: "remera", cantidad: 1, desc: "Una blusa elegante color blanco con mangas enmalladas", precio: 500, talle: "L", img: './img/remera2.jpg'},
    {id: 9, nombre: "Remera 3", tipo: "remera", cantidad: 1, desc: "Una blusa elegante color rosado enmallado", precio: 500, talle: "M", img: './img/remera3.jpg'},
    {id: 10, nombre: "Remera 4", tipo: "remera", cantidad: 1, desc: "Blusa elegante color crema con detalles negros", precio: 700, talle: "M", img: './img/remera4.jpg'},
    {id: 11, nombre: "Remera 5", tipo: "remera", cantidad: 1,desc: "blusa elegante con abertura en v en el escote", precio: 700, talle: "S", img: './img/remera5.jpg'},
    {id: 12, nombre: "Remera 6", tipo: "remera", cantidad: 1, desc: "Blusa elegante color blanco satinado", precio: 700, talle: "S", img: './img/remera6.jpg'},
    {id: 13, nombre: "Camisa 1", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color blanco", precio: 900, talle: "L", img: './img/camisa1.jpg'},
    {id: 14, nombre: "Camisa 2", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color azul oscuro", precio: 1400, talle: "S", img: './img/camisa2.jpg'},
    {id: 15, nombre: "Camisa 3", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color rojo", precio: 7000, talle: "L", img: './img/camisa3.jpg'},
    {id: 16, nombre: "Camisa 4", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color azúl celeste", precio: 777, talle: "S", img: './img/camisa4.jpg'},
    {id: 17, nombre: "Camisa 5", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color blanco", precio: 234, talle: "S", img: './img/camisa5.jpg'},
    {id: 18, nombre: "Camisa 6", tipo: "camisa", cantidad: 1, desc: "Una camisa elegante color azúl", precio: 155600, talle: "M", img: './img/camisa6.jpg'},
    {id: 24, nombre: "Pantalon 6", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color azul oscuro", precio: 800, talle: "S", img: './img/pantalon5.jpg'},
    {id: 19, nombre: "Pantalon 1", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color gris", precio: 1600, talle: "L", img: './img/pantalon.jpg'},
    {id: 20, nombre: "Pantalon 2", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color gris claro", precio: 3200, talle: "L", img: './img/pantalon1.jpg'},
    {id: 21, nombre: "Pantalon 3", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color azul ", precio: 2300, talle: "M", img: './img/pantalon6.jpg'},
    {id: 22, nombre: "Pantalon 4", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color negro", precio: 5600, talle: "M", img: './img/pantalon3.jpg'},
    {id: 23, nombre: "Pantalon 5", tipo: "pantalon", cantidad: 1, desc: "Pantalon elegante color camel", precio: 1700, talle: "S", img: './img/pantalon4.jpg'},
]